import cv2
import time
from pathlib import Path 
from fastapi import APIRouter, Query # Import Query for parsing query parameters in the capture endpoint and APIRouter for defining routes in a modular way
from fastapi.responses import StreamingResponse, JSONResponse # StreamingResponse: stream video frames to the client; JSONResponse: return JSON responses for errors and other data
from .camera import get_camera
from .config import CAPTURE_DIR, VALID_CLASSES

router = APIRouter() # Can be imported and used in the main application

@router.get("/health") # @router.get defines a GET endpoint at /health, that means that when a client sends a GET request to /health, the health function will be called
def health():
    return {"status": "ok"}

@router.get("/classes")
def classes():
    return {"classes": VALID_CLASSES}

@router.post("/capture")
def capture(class_name: str = Query(...)):
    if class_name not in VALID_CLASSES:
        return JSONResponse(status_code=400, content={"error": f"Invalid class: {class_name}"})
    camera = get_camera()
    ok, frame = camera.read()
    if not ok:
        return JSONResponse(status_code=500, content={"error": "Failed to read frame"})
    save_dir = CAPTURE_DIR / class_name
    save_dir.mkdir(parents=True, exist_ok=True)
    filename = save_dir / f"{int(time.time() * 1000)}.jpg"
    cv2.imwrite(str(filename), frame)
    return {"saved": str(filename)}

@router.get("/stats") # Return the number of captured images for each class
def stats():
    results = {}
    for cls in VALID_CLASSES:
        cls_dir = CAPTURE_DIR / cls
        results[cls] = len(list(cls_dir.glob("*.jpg"))) if cls_dir.exists() else 0
    return results

def _generate_frames():
    cam = get_camera()
    while True:
        ok, frame = cam.read()
        if not ok:
            break
        _, buffer = cv2.imencode('.jpg', frame) # imencode: encode the frame as a JPEG image in memory
        # yield: return a continuos frames to a client, as they are generated by the camera
        yield (
            b"--frame\r\n"
            b"Content-Type: image/jpeg\r\n\r\n"
            + buffer.tobytes() 
            + b"\r\n"
        )
        
@router.get("/stream") # Stream video frames to the client using multipart/x-mixed-replace content type, which allows sending multiple frames in a single response
def stream():
    return StreamingResponse(
        _generate_frames(),
        media_type="multipart/x-mixed-replace; boundary=frame"
    )
